[DATALAD] Recorded changes

diff --git a/.github/workflows/matlab_test_and_coverage.yaml b/.github/workflows/matlab_test_and_coverage.yaml
--- a/.github/workflows/matlab_test_and_coverage.yaml
+++ b/.github/workflows/matlab_test_and_coverage.yaml
@@ -1,4 +1,5 @@
-name: "MATLAB: test and coverage"
+---
+name: 'MATLAB: test and coverage'
 
 # Installs
 # - MATLAB github action
@@ -11,9 +12,9 @@ name: "MATLAB: test and coverage"
 
 on:
   push:
-    branches: ["master", "main", "dev"]
+    branches: [master, main, dev]
   pull_request:
-    branches: ["*"]
+    branches: ['*']
 
 jobs:
   matlab_tests:
@@ -27,36 +28,40 @@ jobs:
     runs-on: ${{ matrix.os }}
 
     steps:
-      - name: Install MATLAB
-        uses: matlab-actions/setup-matlab@v1.2.4
-        with:
-          release: ${{ matrix.version }}
+    - name: Install MATLAB
+      uses: matlab-actions/setup-matlab@v1.2.4
+      with:
+        release: ${{ matrix.version }}
 
-      - uses: actions/checkout@v3
-        with:
-          submodules: true
-          fetch-depth: 1
+    - uses: actions/checkout@v3
+      with:
+        submodules: true
+        fetch-depth: 1
 
-      - name: Install Moxunit and MOcov
-        run: |
-          git clone https://github.com/MOxUnit/MOxUnit.git --depth 1
-          git clone https://github.com/MOcov/MOcov.git --depth 1
+    - name: Install Moxunit and MOcov
+      run: |
+        git clone https://github.com/MOxUnit/MOxUnit.git --depth 1
+        git clone https://github.com/MOcov/MOcov.git --depth 1
 
-      - name: Run tests
-        uses: matlab-actions/run-command@v1.1.3
-        with:
-          command:
-            cd(fullfile(getenv('GITHUB_WORKSPACE'), '.github', 'workflows'));
-            run run_tests_ci;
+    - name: Run tests
+      uses: matlab-actions/run-command@v1.1.3
+      with:
+        command: cd(fullfile(getenv('GITHUB_WORKSPACE'), '.github', 'workflows')); run run_tests_ci;
 
-      - name: Check logs
-        run: |
-          cat test_report.log | grep 0
+    - name: Check logs unix
+      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
+      run: grep -q 0 test_report.log || { echo "Some tests failed. Check the 'Run tests' step to know which ones." >&2; exit 1; }
+    - name: Check logs windows
+      if: matrix.os == 'windows-latest'
+      run: |
+        if (-not (Get-Content test_report.log | Select-String -Pattern "0")) {
+          throw "Some tests failed.  Check the 'Run tests' step to know which ones."
+        }
 
-      - name: Code coverage
-        uses: codecov/codecov-action@v3
-        with:
-          file: coverage.xml # optional
-          flags: matlab # optional
-          name: codecov-umbrella # optional
-          fail_ci_if_error: true # optional (default = false)
+    - name: Code coverage
+      uses: codecov/codecov-action@v3
+      with:
+        file: coverage.xml   # optional
+        flags: matlab   # optional
+        name: codecov-umbrella   # optional
+        fail_ci_if_error: true   # optional (default = false)
